[project]
name = "wardogs-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "iiTzArcur",email = "zefanjaj@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "discord-py (>=2.7.1,<3.0.0)",
    "environs (>=15.2.0,<16.0.0)",
    "sqlalchemy (>=2.0.54,<3.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "greenlet (>=3.5.6,<4.0.0)",
    "pyjwt (>=2.14.0,<3.0.0)",
    "microsoft-kiota-abstractions (>=1.11.9,<2.0.0)",
    "microsoft-kiota-http (>=1.11.9,<2.0.0)",
    "microsoft-kiota-serialization-json (>=1.11.9,<2.0.0)",
    "microsoft-kiota-serialization-text (>=1.11.9,<2.0.0)",
    "microsoft-kiota-serialization-form (>=1.11.9,<2.0.0)",
    "microsoft-kiota-serialization-multipart (>=1.11.9,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
